=== Klortho/Eutils-JSON/samples/eInfo_020511.dtd
<!--
  This is a version of the DTD for Entrez eInfo,
  which has been enhanced with DtdAnalzyer annotaions.
-->

<!-- ================================================================= -->

<!--~~ !dtd
~~json 
    <json type='einfo' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!--~~ <eInfoResult>
This is the root element for an EInfo response.
~~ tags root
~~-->
<!ELEMENT       eInfoResult     (DbList|DbInfo|ERROR)>

<!ELEMENT       DbName          (#PCDATA)>      <!-- \S+ -->
<!ELEMENT       Name            (#PCDATA)>      <!-- .+ -->
<!ELEMENT       FullName        (#PCDATA)>      <!-- .+ -->
<!ELEMENT       Description     (#PCDATA)>      <!-- .+ -->
<!ELEMENT       TermCount       (#PCDATA)>      <!-- \d+ -->
<!ELEMENT       Menu            (#PCDATA)>      <!-- .+ -->
<!ELEMENT       DbTo            (#PCDATA)>      <!-- \S+ -->
<!ELEMENT       MenuName        (#PCDATA)>      <!-- .+ -->
<!ELEMENT       Count           (#PCDATA)>      <!-- \d+ -->
<!ELEMENT       LastUpdate      (#PCDATA)>      <!-- \d+ -->

<!--~~ <ERROR>
~~ json <json name="'ERROR'"/>
~~-->
<!ELEMENT       ERROR           (#PCDATA)>      <!-- .+ -->

<!ELEMENT       IsDate          (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       IsNumerical     (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       SingleToken     (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       Hierarchy       (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       IsHidden        (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       IsRangable      (#PCDATA)>      <!-- (Y|N) -->
<!ELEMENT       IsTruncatable   (#PCDATA)>      <!-- (Y|N) -->


<!ELEMENT       DbList          (DbName+)>

<!ELEMENT       Field           (Name,
                                 FullName,
                                 Description,
                                 TermCount,
                                 IsDate,
                                 IsNumerical,
                                 SingleToken,
                                 Hierarchy,
                                 IsHidden,
                                 IsRangable?,
                                 IsTruncatable?)>

<!ELEMENT       Link            (Name,Menu,Description,DbTo)>

<!ELEMENT       LinkList        (Link*)>
<!ELEMENT       FieldList       (Field*)>


<!ELEMENT       DbInfo          (DbName,
                                 MenuName,
                                 Description,
                                 Count,
                                 LastUpdate,
                                 FieldList,
                                 LinkList?)>

=== Klortho/Eutils-JSON/samples/einfo.xml
<?xml version="1.0"?>
<!DOCTYPE eInfoResult PUBLIC "-//NLM//DTD eInfoResult, 11 May 2002//EN" 
  "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eInfo_020511.dtd">

<eInfoResult>
    <DbList>
        <DbName>pubmed</DbName>
        <DbName>protein</DbName>
        <DbName>nuccore</DbName>
        <DbName>nucleotide</DbName>
        <DbName>nucgss</DbName>
        <DbName>nucest</DbName>
        <DbName>structure</DbName>
        <DbName>genome</DbName>
        <DbName>assembly</DbName>
        <DbName>gcassembly</DbName>
        <DbName>genomeprj</DbName>
        <DbName>bioproject</DbName>
        <DbName>biosample</DbName>
        <DbName>biosystems</DbName>
        <DbName>blastdbinfo</DbName>
        <DbName>books</DbName>
        <DbName>cdd</DbName>
        <DbName>clone</DbName>
        <DbName>gap</DbName>
        <DbName>gapplus</DbName>
        <DbName>dbvar</DbName>
        <DbName>epigenomics</DbName>
        <DbName>gene</DbName>
        <DbName>gds</DbName>
        <DbName>geo</DbName>
        <DbName>geoprofiles</DbName>
        <DbName>homologene</DbName>
        <DbName>journals</DbName>
        <DbName>medgen</DbName>
        <DbName>mesh</DbName>
        <DbName>ncbisearch</DbName>
        <DbName>nlmcatalog</DbName>
        <DbName>omia</DbName>
        <DbName>omim</DbName>
        <DbName>pmc</DbName>
        <DbName>popset</DbName>
        <DbName>probe</DbName>
        <DbName>proteinclusters</DbName>
        <DbName>pcassay</DbName>
        <DbName>pccompound</DbName>
        <DbName>pcsubstance</DbName>
        <DbName>pubmedhealth</DbName>
        <DbName>seqannot</DbName>
        <DbName>snp</DbName>
        <DbName>sra</DbName>
        <DbName>taxonomy</DbName>
        <DbName>toolkit</DbName>
        <DbName>toolkitall</DbName>
        <DbName>unigene</DbName>
        <DbName>unists</DbName>
        <DbName>gencoll</DbName>
    </DbList>
</eInfoResult>
