=== Klortho/Eutils-JSON/samples/eSummary_pcsubstance.dtd
<!-- DocSum DTD for pcsubstance database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_int		"(#PCDATA)">
<!ENTITY	 % T_string		"(#PCDATA)">

<!-- Definition of List type: T_StringList -->
<!ELEMENT	string	%T_string;>
<!ENTITY	 % T_StringList	"(string)*">
<!ENTITY	 % T_date		"(#PCDATA)">

<!-- Definition of List type: T_IntList -->
<!--~~ <int>
~~json <number/>
~~-->
<!ELEMENT	int	%T_int;>
<!ENTITY	 % T_IntList	"(int)*">

<!-- Members definition of Structure type: T_DocSum -->
<!--~~ <SID>
~~json <number/>
~~-->
<!ELEMENT	SID		%T_int;>

<!ELEMENT	SourceNameList		%T_StringList;>
<!ELEMENT	CurrentSourceName		%T_string;>
<!ELEMENT	SourceID		%T_string;>
<!ELEMENT	SourceCategoryList		%T_StringList;>
<!ELEMENT	SourceReleaseDate		%T_date;>
<!ELEMENT	DepositDate		%T_date;>
<!ELEMENT	ModifyDate		%T_date;>
<!ELEMENT	RegistryNumber		%T_string;>
<!ELEMENT	DBUrl		%T_string;>
<!ELEMENT	SBUrl		%T_string;>
<!ELEMENT	SynonymList		%T_StringList;>
<!ELEMENT	MeSHHeadingList		%T_StringList;>
<!ELEMENT	MeSHTermList		%T_StringList;>
<!ELEMENT	PharmActionList		%T_StringList;>
<!ELEMENT	CommentList		%T_StringList;>
<!ELEMENT	IUPACName		%T_string;>
<!ELEMENT	CanonicalSmiles		%T_string;>
<!ELEMENT	IsomericSmiles		%T_string;>

<!--~~ <RotatableBondCount>
~~json <number/>
~~-->
<!ELEMENT	RotatableBondCount		%T_int;>

<!ELEMENT	MolecularFormula		%T_string;>
<!ELEMENT	MolecularWeight		%T_string;>

<!--~~ <TotalFormalCharge>
~~json <number/>
~~-->
<!ELEMENT	TotalFormalCharge		%T_int;>

<!ELEMENT	XLogP		%T_string;>

<!--~~ <HydrogenBondDonorCount>
~~json <number/>
~~-->
<!ELEMENT	HydrogenBondDonorCount		%T_int;>

<!--~~ <HydrogenBondAcceptorCount>
~~json <number/>
~~-->
<!ELEMENT	HydrogenBondAcceptorCount		%T_int;>

<!ELEMENT	Complexity		%T_string;>

<!--~~ <HeavyAtomCount>
~~json <number/>
~~-->
<!ELEMENT	HeavyAtomCount		%T_int;>

<!--~~ <AtomChiralCount>
~~json <number/>
~~-->
<!ELEMENT	AtomChiralCount		%T_int;>

<!--~~ <AtomChiralDefCount>
~~json <number/>
~~-->
<!ELEMENT	AtomChiralDefCount		%T_int;>

<!--~~ <AtomChiralUndefCount>
~~json <number/>
~~-->
<!ELEMENT	AtomChiralUndefCount		%T_int;>

<!--~~ <BondChiralCount>
~~json <number/>
~~-->
<!ELEMENT	BondChiralCount		%T_int;>

<!--~~ <BondChiralDefCount>
~~json <number/>
~~-->
<!ELEMENT	BondChiralDefCount		%T_int;>

<!--~~ <BondChiralUndefCount>
~~json <number/>
~~-->
<!ELEMENT	BondChiralUndefCount		%T_int;>

<!--~~ <IsotopeAtomCount>
~~json <number/>
~~-->
<!ELEMENT	IsotopeAtomCount		%T_int;>

<!--~~ <CovalentUnitCount>
~~json <number/>
~~-->
<!ELEMENT	CovalentUnitCount		%T_int;>

<!--~~ <TautomerCount>
~~json <number/>
~~-->
<!ELEMENT	TautomerCount		%T_int;>

<!ELEMENT	CompoundIDList		%T_IntList;>
<!ELEMENT	TPSA		%T_string;>
<!ELEMENT	AssaySourceNameList		%T_StringList;>
<!ELEMENT	MinAC		%T_string;>
<!ELEMENT	MaxAC		%T_string;>
<!ELEMENT	MinTC		%T_string;>
<!ELEMENT	MaxTC		%T_string;>

<!--~~ <ActiveAidCount>
~~json <number/>
~~-->
<!ELEMENT	ActiveAidCount		%T_int;>

<!--~~ <InactiveAidCount>
~~json <number/>
~~-->
<!ELEMENT	InactiveAidCount		%T_int;>

<!--~~ <TotalAidCount>
~~json <number/>
~~-->
<!ELEMENT	TotalAidCount		%T_int;>

<!ELEMENT	InChIKey		%T_string;>

<!--~~ <ProbeAidCount>
~~json <number/>
~~-->
<!ELEMENT	ProbeAidCount		%T_int;>

<!ELEMENT	HoldUntilDate		%T_date;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			SID
			| SourceNameList
			| CurrentSourceName
			| SourceID
			| SourceCategoryList
			| SourceReleaseDate
			| DepositDate
			| ModifyDate
			| RegistryNumber
			| DBUrl
			| SBUrl
			| SynonymList
			| MeSHHeadingList
			| MeSHTermList
			| PharmActionList
			| CommentList
			| IUPACName
			| CanonicalSmiles
			| IsomericSmiles
			| RotatableBondCount
			| MolecularFormula
			| MolecularWeight
			| TotalFormalCharge
			| XLogP
			| HydrogenBondDonorCount
			| HydrogenBondAcceptorCount
			| Complexity
			| HeavyAtomCount
			| AtomChiralCount
			| AtomChiralDefCount
			| AtomChiralUndefCount
			| BondChiralCount
			| BondChiralDefCount
			| BondChiralUndefCount
			| IsotopeAtomCount
			| CovalentUnitCount
			| TautomerCount
			| CompoundIDList
			| TPSA
			| AssaySourceNameList
			| MinAC
			| MaxAC
			| MinTC
			| MaxTC
			| ActiveAidCount
			| InactiveAidCount
			| TotalAidCount
			| InChIKey
			| ProbeAidCount
			| HoldUntilDate
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json <object/>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.pcsubstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_pcsubstance.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="127317050">
	<SID>127317050</SID>
	<SourceNameList>
		<string>826</string>
		<string>EPO</string>
		<string>SLING Consortium</string>
	</SourceNameList>
	<CurrentSourceName>SLING Consortium</CurrentSourceName>
	<SourceID>30497-EP2292088A1</SourceID>
	<SourceCategoryList>
		<string>Patents</string>
	</SourceCategoryList>
	<SourceReleaseDate>2011/12/03 00:00</SourceReleaseDate>
	<DepositDate>2011/12/03 00:00</DepositDate>
	<ModifyDate>2011/12/03 00:00</ModifyDate>
	<RegistryNumber></RegistryNumber>
	<DBUrl></DBUrl>
	<SBUrl></SBUrl>
	<SynonymList>
		<string>30497-EP2292088A1</string>
		<string>CAT</string>
	</SynonymList>
	<MeSHHeadingList>
	</MeSHHeadingList>
	<MeSHTermList>
	</MeSHTermList>
	<PharmActionList>
	</PharmActionList>
	<CommentList>
		<string>&lt;a href=&quot;http://worldwide.espacenet.com/publicationDetails/biblio?FT=D&amp;CC=EP&amp;NR=2292088A1&amp;KC=A1&quot;&gt;Mutant receptors and their use in a nuclear receptor-based inducible gene expression system&lt;/a&gt;</string>
		<string>Patent Number: EP2292088A1</string>
		<string>Publication Date: 2011-03-09</string>
		<string>Classifications: C07K14/435A3, A61K31/16, A61K31/47, C07D215/44, C07H21/04, C12N15/62</string>
		<string>Applicant(s): INTREXON CORP [US]</string>
		<string>Hits: Description</string>
	</CommentList>
	<IUPACName>6-chloro-2-N,4-N-diethyl-1,3,5-triazine-2,4-diamine</IUPACName>
	<CanonicalSmiles>CCNC1=NC(=NC(=N1)Cl)NCC</CanonicalSmiles>
	<IsomericSmiles>CCNC1=NC(=NC(=N1)Cl)NCC</IsomericSmiles>
	<RotatableBondCount>4</RotatableBondCount>
	<MolecularFormula>C7H12ClN5</MolecularFormula>
	<MolecularWeight>    201.656680</MolecularWeight>
	<TotalFormalCharge>0</TotalFormalCharge>
	<XLogP>2.200</XLogP>
	<HydrogenBondDonorCount>2</HydrogenBondDonorCount>
	<HydrogenBondAcceptorCount>5</HydrogenBondAcceptorCount>
	<Complexity>    131.000000</Complexity>
	<HeavyAtomCount>13</HeavyAtomCount>
	<AtomChiralCount>0</AtomChiralCount>
	<AtomChiralDefCount>0</AtomChiralDefCount>
	<AtomChiralUndefCount>0</AtomChiralUndefCount>
	<BondChiralCount>0</BondChiralCount>
	<BondChiralDefCount>0</BondChiralDefCount>
	<BondChiralUndefCount>0</BondChiralUndefCount>
	<IsotopeAtomCount>0</IsotopeAtomCount>
	<CovalentUnitCount>1</CovalentUnitCount>
	<TautomerCount>5</TautomerCount>
	<CompoundIDList>
		<int>5216</int>
	</CompoundIDList>
	<TPSA>62.7</TPSA>
	<AssaySourceNameList>
	</AssaySourceNameList>
	<MinAC></MinAC>
	<MaxAC></MaxAC>
	<MinTC></MinTC>
	<MaxTC></MaxTC>
	<ActiveAidCount>0</ActiveAidCount>
	<InactiveAidCount>0</InactiveAidCount>
	<TotalAidCount>0</TotalAidCount>
	<InChIKey>ODCWYMIRDDJXKW-UHFFFAOYSA-N</InChIKey>
	<ProbeAidCount>0</ProbeAidCount>
	<HoldUntilDate>1/01/01 00:00</HoldUntilDate>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
