=== Klortho/Eutils-JSON/samples/eSummary_gds.dtd
<!-- $Id: eSummary_gds.dtd 363818 2012-05-18 20:58:30Z yasmax $ -->
<!-- DocSum DTD for gds database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">

<!-- Members definition of Structure type: T_Sample -->
<!-- Already defined ...
<!ELEMENT	Accession		%T_string;>
 ... Already defined -->
<!ELEMENT	Title		%T_string;>

<!-- Definition of Structure type: T_Sample -->
<!--~~ <Sample>
~~json <object/>
~~-->
<!ENTITY	 % T_Sample	"(
 			Accession
			| Title
			)*">

<!-- Definition of List type: T_SampleList -->
<!ELEMENT	Sample	%T_Sample;>
<!ENTITY	 % T_SampleList	"(Sample)*">

<!-- Members definition of Structure type: T_Relation -->
<!ELEMENT	RelationType		%T_string;>
<!ELEMENT	TargetObject		%T_string;>

<!-- Definition of Structure type: T_Relation -->
<!--~~ <Relation>
~~json <object/>
~~-->
<!ENTITY	 % T_Relation	"(
 			RelationType
			| TargetObject
			)*">

<!-- Definition of List type: T_RelationList -->
<!ELEMENT	Relation	%T_Relation;>
<!ENTITY	 % T_RelationList	"(Relation)*">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Definition of List type: T_IntList -->
<!--~~ <int>
~~json <number/>
~~-->
<!ELEMENT	int	%T_int;>
<!ENTITY	 % T_IntList	"(int)*">

<!-- Members definition of Structure type: T_Project -->
<!ELEMENT	Name		%T_string;>
<!ELEMENT	URL		%T_string;>

<!-- Definition of Structure type: T_Project -->
<!--~~ <Project>
~~json <object/>
~~-->
<!ENTITY	 % T_Project	"(
 			Name
			| URL
			)*">

<!-- Definition of List type: T_ProjectList -->
<!ELEMENT	Project	%T_Project;>
<!ENTITY	 % T_ProjectList	"(Project)*">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Accession		%T_string;>
<!ELEMENT	GDS		%T_string;>
<!ELEMENT	title		%T_string;>
<!ELEMENT	summary		%T_string;>
<!ELEMENT	GPL		%T_string;>
<!ELEMENT	GSE		%T_string;>
<!ELEMENT	taxon		%T_string;>
<!ELEMENT	entryType		%T_string;>
<!ELEMENT	gdsType		%T_string;>
<!ELEMENT	ptechType		%T_string;>
<!ELEMENT	valType		%T_string;>
<!ELEMENT	SSInfo		%T_string;>
<!ELEMENT	subsetInfo		%T_string;>
<!ELEMENT	PDAT		%T_string;>
<!ELEMENT	suppFile		%T_string;>
<!ELEMENT	Samples		%T_SampleList;>
<!ELEMENT	Relations		%T_RelationList;>
<!ELEMENT	ExtRelations		%T_RelationList;>

<!--~~ <n_samples>
~~json <number/>
~~-->
<!ELEMENT	n_samples		%T_int;>

<!ELEMENT	SeriesTitle		%T_string;>
<!ELEMENT	PlatformTitle		%T_string;>
<!ELEMENT	PlatformTaxa		%T_string;>
<!ELEMENT	SamplesTaxa		%T_string;>
<!ELEMENT	PubMedIds		%T_IntList;>
<!ELEMENT	Projects		%T_ProjectList;>
<!ELEMENT FTPLink %T_string;>
<!ELEMENT GEO2R (#PCDATA)>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			Accession
			| GDS
			| title
			| summary
			| GPL
			| GSE
			| taxon
			| entryType
			| gdsType
			| ptechType
			| valType
			| SSInfo
			| subsetInfo
			| PDAT
			| suppFile
			| Samples
			| Relations
			| ExtRelations
			| n_samples
			| SeriesTitle
			| PlatformTitle
			| PlatformTaxa
			| SamplesTaxa
			| PubMedIds
			| Projects
			| FTPLink
			| GEO2R
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json <object/>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.gds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_gds.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="200040726">
	<Accession>GSE40726</Accession>
	<GDS></GDS>
	<title>Transcriptional profiling of IRF4 -/- vs IRF4 +/- T-cells under Th17 polarizing conditions</title>
	<summary>Transcriptional profiling of T-cells isolated from spleen of IRF4 -/- mice and cultured under Th17 polarizing conditions for 42 hrs compared to cells similarly isolated and cultured from spleen of IRF4 +/- mice. The aim of the study was to identify global misexpression of genes in IRF4 -/- cells and hence identify key pathways regulated by IRF4 during Th17 differentiation.</summary>
	<GPL>7202</GPL>
	<GSE>40726</GSE>
	<taxon>Mus musculus</taxon>
	<entryType>GSE</entryType>
	<gdsType>Expression profiling by array</gdsType>
	<ptechType></ptechType>
	<valType></valType>
	<SSInfo></SSInfo>
	<subsetInfo></subsetInfo>
	<PDAT>2012/09/13</PDAT>
	<suppFile>TXT</suppFile>
	<Samples>
		<Sample>
			<Accession>GSM999794</Accession>
			<Title>IRF4-mut_Th17_cells_42hr_rep1</Title>
		</Sample>
		<Sample>
			<Accession>GSM999797</Accession>
			<Title>IRF4-control_Th17_cells_42hr_rep1</Title>
		</Sample>
		<Sample>
			<Accession>GSM999796</Accession>
			<Title>IRF4-mut_Th17_cells_42hr_rep3</Title>
		</Sample>
		<Sample>
			<Accession>GSM999799</Accession>
			<Title>IRF4-control_Th17_cells_42hr_rep3</Title>
		</Sample>
		<Sample>
			<Accession>GSM999795</Accession>
			<Title>IRF4-mut_Th17_cells_42hr_rep2</Title>
		</Sample>
		<Sample>
			<Accession>GSM999798</Accession>
			<Title>IRF4-control_Th17_cells_42hr_rep2</Title>
		</Sample>
	</Samples>
	<Relations>
	</Relations>
	<ExtRelations>
	</ExtRelations>
	<n_samples>6</n_samples>
	<SeriesTitle></SeriesTitle>
	<PlatformTitle></PlatformTitle>
	<PlatformTaxa></PlatformTaxa>
	<SamplesTaxa></SamplesTaxa>
	<PubMedIds>
		<int>22983707</int>
	</PubMedIds>
	<Projects>
	</Projects>
	<FTPLink>ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE40nnn/GSE40726/</FTPLink>
	<GEO2R>yes</GEO2R>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
