=== Klortho/Eutils-JSON/samples/eSummary_journals.dtd
<!-- DocSum DTD for journals database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">

<!-- Definition of List type: T_StringList -->
<!ELEMENT	string	%T_string;>
<!ENTITY	 % T_StringList	"(string)*">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Title		%T_string;>
<!ELEMENT	MedAbbr		%T_string;>
<!ELEMENT	IsoAbbr		%T_string;>
<!ELEMENT	NlmId		%T_string;>
<!ELEMENT	pISSN		%T_string;>
<!ELEMENT	eISSN		%T_string;>
<!ELEMENT	PublicationStartYear		%T_string;>
<!ELEMENT	PublicationEndYear		%T_string;>
<!ELEMENT	Publisher		%T_string;>
<!ELEMENT	Language		%T_string;>
<!ELEMENT	Country		%T_string;>
<!ELEMENT	BroadHeading		%T_StringList;>
<!ELEMENT	ContinuationNotes		%T_string;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			Title
			| MedAbbr
			| IsoAbbr
			| NlmId
			| pISSN
			| eISSN
			| PublicationStartYear
			| PublicationEndYear
			| Publisher
			| Language
			| Country
			| BroadHeading
			| ContinuationNotes
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json 
  <object name='"result"'>
    <array name='"uids"' select='DocumentSummary/@uid'/>
    <members select='DocumentSummary'/>
  </object>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~ json <member/>
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.journals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_journals.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="35478">
	<Title>The National union catalog of manuscript collections</Title>
	<MedAbbr>Natl Union Cat Manuscr Collect</MedAbbr>
	<IsoAbbr>Natl Union Cat Manuscr Collect</IsoAbbr>
	<NlmId>58720840R</NlmId>
	<pISSN>0090-0044</pISSN>
	<eISSN></eISSN>
	<PublicationStartYear>1959</PublicationStartYear>
	<PublicationEndYear>1993</PublicationEndYear>
	<Publisher>U.S. Library Of Congress</Publisher>
	<Language>eng</Language>
	<Country>United States</Country>
	<BroadHeading>
	</BroadHeading>
	<ContinuationNotes></ContinuationNotes>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
