=== Klortho/Eutils-JSON/samples/eSummary_proteinclusters.dtd
<!-- DocSum DTD for proteinclusters database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">
<!ENTITY	 % T_date		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ELEMENT	ACCN		%T_string;>
<!ELEMENT	Definition		%T_string;>

<!--~~ <Total_Prots>
~~json <number/>
~~-->
<!ELEMENT	Total_Prots		%T_int;>

<!--~~ <Total_genera>
~~json <number/>
~~-->
<!ELEMENT	Total_genera		%T_int;>

<!--~~ <Total_dups>
~~json <number/>
~~-->
<!ELEMENT	Total_dups		%T_int;>

<!ELEMENT	Pmids		%T_string;>
<!ELEMENT	Gene		%T_string;>
<!ELEMENT	GeneSynonym		%T_string;>
<!ELEMENT	Comment		%T_string;>
<!ELEMENT	COG		%T_string;>
<!ELEMENT	EC		%T_string;>
<!ELEMENT	HAMAP		%T_string;>
<!ELEMENT	KO		%T_string;>
<!ELEMENT	CreateDate		%T_date;>
<!ELEMENT	ModDate		%T_date;>

<!--~~ <Domains>
~~json <number/>
~~-->
<!ELEMENT	Domains		%T_int;>

<!ELEMENT	CommonTaxonomy		%T_string;>

<!--~~ <Paralogs>
~~json <number/>
~~-->
<!ELEMENT	Paralogs		%T_int;>

<!ELEMENT	COGgroup		%T_string;>

<!--~~ <AverageLength>
~~json <number/>
~~-->
<!ELEMENT	AverageLength		%T_int;>

<!--~~ <Total_Publications>
~~json <number/>
~~-->
<!ELEMENT	Total_Publications		%T_int;>

<!ELEMENT	Source		%T_string;>

<!-- Definition of Structure type: T_DocSum -->
<!ENTITY	 % T_DocSum	"(
 			ACCN
			| Definition
			| Total_Prots
			| Total_genera
			| Total_dups
			| Pmids
			| Gene
			| GeneSynonym
			| Comment
			| COG
			| EC
			| HAMAP
			| KO
			| CreateDate
			| ModDate
			| Domains
			| CommonTaxonomy
			| Paralogs
			| COGgroup
			| AverageLength
			| Total_Publications
			| Source
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json 
  <object key="result">
    <array key="uids" select='DocumentSummary/@uid'/>
    <members select='DocumentSummary'/>
  </object>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ json <member/>
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.proteinclusters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_proteinclusters.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="2516486">
	<ACCN>PRK14674</ACCN>
	<Definition>hypothetical protein</Definition>
	<Total_Prots>9</Total_Prots>
	<Total_genera>1</Total_genera>
	<Total_dups>0</Total_dups>
	<Pmids></Pmids>
	<Gene>None</Gene>
	<GeneSynonym>None</GeneSynonym>
	<Comment></Comment>
	<COG>COG0792L</COG>
	<EC></EC>
	<HAMAP>MF_00048</HAMAP>
	<KO>K07460</KO>
	<CreateDate>2009/08/27 00:00</CreateDate>
	<ModDate>2012/04/13 00:00</ModDate>
	<Domains>1</Domains>
	<CommonTaxonomy>Acinetobacter</CommonTaxonomy>
	<Paralogs>0</Paralogs>
	<COGgroup>Replication, recombination and repair</COGgroup>
	<AverageLength>133</AverageLength>
	<Total_Publications>5</Total_Publications>
	<Source>genomic</Source>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
