=== Klortho/Eutils-JSON/samples/eSummary_biosystems.dtd
<!-- $Id: eSummary_biosystems.dtd 363818 2012-05-18 20:58:30Z yasmax $ -->
<!-- DocSum DTD for biosystems database -->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_date		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Definition of List type: T_categorylist -->
<!ELEMENT	string	%T_string;>
<!ENTITY	 % T_categorylist	"(string)*">

<!-- Members definition of Structure type: T_citation -->
<!ELEMENT	pmid		%T_int;>
<!ELEMENT	textcitation		%T_string;>
<!ELEMENT	category		%T_categorylist;>

<!-- Definition of Structure type: T_citation -->
<!ENTITY	 % T_citation	"(
 			pmid
			| textcitation
			| category
			)*">

<!-- Definition of List type: T_citationlist -->
<!ELEMENT	citation	%T_citation;>
<!ENTITY	 % T_citationlist	"(citation)*">

<!-- Definition of List type: T_commentlist -->
<!-- Already defined ...
<!ELEMENT	string	%T_string;>
 ... Already defined -->
<!ENTITY	 % T_commentlist	"(string)*">

<!-- Definition of Enumeration type: T_highlightenum -->
<!ENTITY	 % T_highlightenum		"(#PCDATA)">

<!-- Definition of Enumeration type: T_idtypesenum -->
<!ENTITY	 % T_idtypesenum		"(#PCDATA)">

<!-- Definition of List type: T_idtypeslist -->
<!ELEMENT	idtypesenum	%T_idtypesenum;>
<!ENTITY	 % T_idtypeslist	"(idtypesenum)*">

<!-- Members definition of Structure type: T_highliteurlstruct -->
<!ELEMENT	hilitetype		%T_highlightenum;>
<!ELEMENT	idtypes		%T_idtypeslist;>
<!-- Already defined ...
<!ELEMENT	url		%T_string;>
 ... Already defined -->

<!-- Definition of Structure type: T_highliteurlstruct -->
<!ENTITY	 % T_highliteurlstruct	"(
 			hilitetype
			| idtypes
			| url
			)*">

<!-- Members definition of Structure type: T_taxnodestruct -->
<!ELEMENT	taxid		%T_int;>
<!ELEMENT	taxonomyname		%T_string;>

<!-- Definition of Structure type: T_taxnodestruct -->
<!ENTITY	 % T_taxnodestruct	"(
 			taxid
			| taxonomyname
			)*">

<!-- Definition of List type: T_taxonomylist -->
<!ELEMENT	taxnodestruct	%T_taxnodestruct;>
<!ENTITY	 % T_taxonomylist	"(taxnodestruct)*">

<!-- Definition of List type: T_namelist -->
<!-- Already defined ...
<!ELEMENT	string	%T_string;>
 ... Already defined -->
<!ENTITY	 % T_namelist	"(string)*">

<!-- Members definition of Structure type: T_geneidstruct -->
<!ELEMENT	geneid		%T_int;>
<!ELEMENT	genename		%T_string;>
<!-- Already defined ...
<!ELEMENT	description		%T_string;>
 ... Already defined -->

<!-- Definition of Structure type: T_geneidstruct -->
<!ENTITY	 % T_geneidstruct	"(
 			geneid
			| genename
			| description
			)*">

<!-- Members definition of Structure type: T_proteinstruct -->
<!ELEMENT	gi		%T_int;>
<!ELEMENT	accession		%T_string;>
<!-- Already defined ...
<!ELEMENT	description		%T_string;>
 ... Already defined -->

<!-- Definition of Structure type: T_proteinstruct -->
<!ENTITY	 % T_proteinstruct	"(
 			gi
			| accession
			| description
			)*">

<!-- Definition of List type: T_proteinlist -->
<!ELEMENT	proteinstruct	%T_proteinstruct;>
<!ENTITY	 % T_proteinlist	"(proteinstruct)*">

<!-- Members definition of Structure type: T_entitystruct -->
<!ELEMENT	gene		%T_geneidstruct;>
<!ELEMENT	protein		%T_proteinlist;>

<!-- Definition of Structure type: T_entitystruct -->
<!ENTITY	 % T_entitystruct	"(
 			gene
			| protein
			)*">

<!-- Definition of List type: T_entitylist -->
<!ELEMENT	entitystruct	%T_entitystruct;>
<!ENTITY	 % T_entitylist	"(entitystruct)*">

<!-- Members definition of Structure type: T_propertystruct -->
<!ELEMENT	propertyname		%T_string;>
<!ELEMENT	propertyvalue		%T_string;>

<!-- Definition of Structure type: T_propertystruct -->
<!ENTITY	 % T_propertystruct	"(
 			propertyname
			| propertyvalue
			)*">

<!-- Definition of List type: T_propertylist -->
<!ELEMENT	propertystruct	%T_propertystruct;>
<!ENTITY	 % T_propertylist	"(propertystruct)*">

<!-- Members definition of Structure type: T_genestruct -->
<!-- Already defined ...
<!ELEMENT	externalid		%T_string;>
 ... Already defined -->
<!ELEMENT	names		%T_namelist;>
<!-- Already defined ...
<!ELEMENT	comment		%T_commentlist;>
 ... Already defined -->
<!ELEMENT	entity		%T_entitylist;>
<!-- Already defined ...
<!ELEMENT	category		%T_categorylist;>
 ... Already defined -->
<!ELEMENT	property		%T_propertylist;>

<!-- Definition of Structure type: T_genestruct -->
<!ENTITY	 % T_genestruct	"(
 			externalid
			| names
			| comment
			| entity
			| category
			| property
			)*">

<!-- Definition of List type: T_genelist -->
<!ELEMENT	genestruct	%T_genestruct;>
<!ENTITY	 % T_genelist	"(genestruct)*">

<!-- Members definition of Structure type: T_smallmoleculestruct -->
<!-- Already defined ...
<!ELEMENT	externalid		%T_string;>
 ... Already defined -->
<!ELEMENT	moleculenames		%T_namelist;>
<!-- Already defined ...
<!ELEMENT	comment		%T_commentlist;>
 ... Already defined -->
<!ELEMENT	sid		%T_int;>
<!ELEMENT	cid		%T_int;>
<!-- Already defined ...
<!ELEMENT	category		%T_categorylist;>
 ... Already defined -->
<!-- Already defined ...
<!ELEMENT	property		%T_propertylist;>
 ... Already defined -->

<!-- Definition of Structure type: T_smallmoleculestruct -->
<!ENTITY	 % T_smallmoleculestruct	"(
 			externalid
			| moleculenames
			| comment
			| sid
			| cid
			| category
			| property
			)*">

<!-- Definition of List type: T_smallmoleculelist -->
<!ELEMENT	smallmoleculestruct	%T_smallmoleculestruct;>
<!ENTITY	 % T_smallmoleculelist	"(smallmoleculestruct)*">

<!-- Definition of Enumeration type: T_linkedsystemenum -->
<!ENTITY	 % T_linkedsystemenum		"(#PCDATA)">

<!-- Members definition of Structure type: T_linkedsystemstruct -->
<!-- Already defined ...
<!ELEMENT	externalid		%T_string;>
 ... Already defined -->
<!ELEMENT	bsid		%T_int;>
<!ELEMENT	linkedsystemname		%T_string;>
<!ELEMENT	linkedsystemtype		%T_linkedsystemenum;>

<!-- Definition of Structure type: T_linkedsystemstruct -->
<!ENTITY	 % T_linkedsystemstruct	"(
 			externalid
			| bsid
			| linkedsystemname
			| linkedsystemtype
			)*">

<!-- Definition of List type: T_linkedsystemlist -->
<!ELEMENT	linkedsystemstruct	%T_linkedsystemstruct;>
<!ENTITY	 % T_linkedsystemlist	"(linkedsystemstruct)*">

<!-- Members definition of Structure type: T_biosystemstruct -->
<!ELEMENT	externalid		%T_string;>
<!ELEMENT	biosystemname		%T_string;>
<!ELEMENT	biosystemtype		%T_string;>
<!ELEMENT	bscategory		%T_string;>
<!ELEMENT	bstype		%T_string;>
<!ELEMENT	description		%T_string;>
<!ELEMENT	comment		%T_commentlist;>
<!ELEMENT	url		%T_string;>
<!ELEMENT	highliteurl		%T_highliteurlstruct;>
<!ELEMENT	taxonomy		%T_taxonomylist;>
<!ELEMENT	genes		%T_genelist;>
<!ELEMENT	smallmolecules		%T_smallmoleculelist;>
<!-- Already defined ...
<!ELEMENT	citations		%T_citationlist;>
 ... Already defined -->
<!ELEMENT	linkedsystems		%T_linkedsystemlist;>

<!-- Definition of Structure type: T_biosystemstruct -->
<!ENTITY	 % T_biosystemstruct	"(
 			externalid
			| biosystemname
			| biosystemtype
			| bscategory
			| bstype
			| description
			| comment
			| url
			| highliteurl
			| taxonomy
			| genes
			| smallmolecules
			| citations
			| linkedsystems
			)*">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	source		%T_string;>
<!ELEMENT	ModifyDate		%T_date;>
<!ELEMENT	SIDCount		%T_int;>
<!ELEMENT	CIDCount		%T_int;>
<!ELEMENT	GeneCount		%T_int;>
<!ELEMENT	ProteinCount		%T_int;>
<!ELEMENT	feedbackurl		%T_string;>
<!ELEMENT	sourceurl		%T_string;>
<!ELEMENT	citations		%T_citationlist;>
<!ELEMENT	biosystem		%T_biosystemstruct;>

<!-- Definition of Structure type: T_DocSum -->
<!ENTITY	 % T_DocSum	"(
 			source
			| ModifyDate
			| SIDCount
			| CIDCount
			| GeneCount
			| ProteinCount
			| feedbackurl
			| sourceurl
			| citations
			| biosystem
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.biosystems.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_biosystems.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="493040">
	<source>GO</source>
	<ModifyDate>2011/11/04 00:00</ModifyDate>
	<SIDCount>0</SIDCount>
	<CIDCount>0</CIDCount>
	<GeneCount>3</GeneCount>
	<ProteinCount>5</ProteinCount>
	<feedbackurl>http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0008811</feedbackurl>
	<sourceurl>http://www.geneontology.org/</sourceurl>
	<citations>
	</citations>
	<biosystem>
		<externalid>GO:0008811</externalid>
		<biosystemname>chloramphenicol O-acetyltransferase activity</biosystemname>
		<biosystemtype>conserved biosystem</biosystemtype>
		<bscategory>conserved biosystem</bscategory>
		<bstype>functional_set</bstype>
		<description>Catalysis of the reaction: acetyl-CoA + chloramphenicol = chloramphenicol 3-acetate + CoA. Synonyms: CAT I; CAT II; CAT III; acetyl-CoA:chloramphenicol 3-O-acetyltransferase activity; chloramphenicol acetylase activity; chloramphenicol acetyltransferase activity; chloramphenicol transacetylase activity;</description>
		<comment>
		</comment>
		<url>http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0008811</url>
		<highliteurl>
			<hilitetype>
				simple
			</hilitetype>
			<idtypes>
			</idtypes>
			<url></url>
		</highliteurl>
		<taxonomy>
		</taxonomy>
		<genes>
		</genes>
		<smallmolecules>
		</smallmolecules>
		<citations>
		</citations>
		<linkedsystems>
		</linkedsystems>
	</biosystem>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
