=== Klortho/Eutils-JSON/samples/eSummary_geo.dtd
<!-- DocSum DTD for geo database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	GDS		%T_string;>
<!ELEMENT	ERANK		%T_string;>
<!ELEMENT	EVALUE		%T_string;>
<!ELEMENT	title		%T_string;>
<!ELEMENT	summary		%T_string;>
<!ELEMENT	GPL		%T_string;>
<!ELEMENT	GSE		%T_string;>
<!ELEMENT	taxon		%T_string;>
<!ELEMENT	taxid_L		%T_string;>
<!ELEMENT	GSM_L		%T_string;>
<!ELEMENT	gdsType		%T_string;>
<!ELEMENT	valType		%T_string;>
<!ELEMENT	idref		%T_string;>
<!ELEMENT	ORF		%T_string;>
<!ELEMENT	geneDesc		%T_string;>
<!ELEMENT	geneName		%T_string;>
<!ELEMENT	nucDesc		%T_string;>
<!ELEMENT	UGName		%T_string;>
<!ELEMENT	UGDesc		%T_string;>
<!ELEMENT	cloneID		%T_string;>
<!ELEMENT	GBACC		%T_string;>
<!ELEMENT	PTACC		%T_string;>
<!ELEMENT	SPOTID		%T_string;>
<!ELEMENT	gi		%T_string;>
<!ELEMENT	SAGEmap		%T_string;>
<!ELEMENT	alias		%T_string;>
<!ELEMENT	SUB_SAMP_L		%T_string;>
<!ELEMENT	SUB_TYPES_L		%T_string;>
<!ELEMENT	VMIN		%T_string;>
<!ELEMENT	VMAX		%T_string;>
<!ELEMENT	outliers		%T_string;>
<!ELEMENT	abscalls_chain		%T_string;>

<!--~~ <AFLAG>
~~json <number/>
~~-->
<!ELEMENT	AFLAG		%T_int;>

<!--~~ <AOUTL>
~~json <number/>
~~-->
<!ELEMENT	AOUTL		%T_int;>

<!--~~ <RSTD>
~~json <number/>
~~-->
<!ELEMENT	RSTD		%T_int;>

<!--~~ <RMEAN>
~~json <number/>
~~-->
<!ELEMENT	RMEAN		%T_int;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			GDS
			| ERANK
			| EVALUE
			| title
			| summary
			| GPL
			| GSE
			| taxon
			| taxid_L
			| GSM_L
			| gdsType
			| valType
			| idref
			| ORF
			| geneDesc
			| geneName
			| nucDesc
			| UGName
			| UGDesc
			| cloneID
			| GBACC
			| PTACC
			| SPOTID
			| gi
			| SAGEmap
			| alias
			| SUB_SAMP_L
			| SUB_TYPES_L
			| VMIN
			| VMAX
			| outliers
			| abscalls_chain
			| AFLAG
			| AOUTL
			| RSTD
			| RMEAN
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json 
  <object name='"result"'>
    <array name='"uids"' select='DocumentSummary/@uid'/>
    <members select='DocumentSummary'/>
  </object>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~ json <member/>
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.geo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_geo.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="65685298">
	<GDS>3717</GDS>
	<ERANK>816lkZbQjK26</ERANK>
	<EVALUE>946zyS-TgA05</EVALUE>
	<title>NOTCH antagonist SAHM1 effect on T-ALL cell lines</title>
	<summary>Analysis of HPB-ALL and KOPT-K1 cells treated with SAHM1, an antagonist of the NOTCH transcription factor. SAHM1 is an alpha-helical hydrocarbon stapled peptide derived from MAML1. Results provide insight into the specificity of the antagonistic effect of SAHM1 on gene expression driven by NOTCH.</summary>
	<GPL>570</GPL>
	<GSE>18198</GSE>
	<taxon>Homo sapiens</taxon>
	<taxid_L>9606</taxid_L>
	<GSM_L>455115p1p1p4p1p1m5p1p1p4p1p1</GSM_L>
	<gdsType>Expression profiling by array</gdsType>
	<valType>transformed count</valType>
	<idref>243048_at</idref>
	<ORF></ORF>
	<geneDesc>cat eye syndrome chromosome region, candidate 7 (non-protein coding)</geneDesc>
	<geneName>CECR7</geneName>
	<nucDesc>aa73g04.s1 NCI_CGAP_GCB1 Homo sapiens cDNA clone IMAGE:826614 3-, mRNA sequence</nucDesc>
	<UGName></UGName>
	<UGDesc></UGDesc>
	<cloneID></cloneID>
	<GBACC>AA521486</GBACC>
	<PTACC></PTACC>
	<SPOTID></SPOTID>
	<gi>2262029</gi>
	<SAGEmap></SAGEmap>
	<alias>FLJ40726, SAHL1</alias>
	<SUB_SAMP_L>455115p1p1p4p1p1;455118p1p1p4p1p1;455115p1p1p1p1p1;455121p1p1p1p1p1</SUB_SAMP_L>
	<SUB_TYPES_L>6;6;9;9</SUB_TYPES_L>
	<VMIN>0.862716</VMIN>
	<VMAX>1.123969</VMAX>
	<outliers></outliers>
	<abscalls_chain></abscalls_chain>
	<AFLAG>5625</AFLAG>
	<AOUTL>0</AOUTL>
	<RSTD>14</RSTD>
	<RMEAN>52</RMEAN>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
