=== Klortho/Eutils-JSON/samples/eSummary_blastdbinfo.dtd
<!-- DocSum DTD for blastdbinfo database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_date		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Members definition of Structure type: T_SourceDbData -->
<!ELEMENT	SrcDb		%T_string;>

<!-- Definition of Structure type: T_SourceDbData -->
<!ENTITY	 % T_SourceDbData	"(
 			SrcDb
			)*">

<!-- Definition of List type: T_SourceDbType -->
<!ELEMENT	SourceDbData	%T_SourceDbData;>
<!ENTITY	 % T_SourceDbType	"(SourceDbData)*">

<!-- Members definition of Structure type: T_SequenceTypeData -->
<!ELEMENT	SeqType		%T_string;>
<!ELEMENT	SeqStrategy		%T_string;>

<!-- Definition of Structure type: T_SequenceTypeData -->
<!ENTITY	 % T_SequenceTypeData	"(
 			SeqType
			| SeqStrategy
			)*">

<!-- Definition of List type: T_SequenceTypeType -->
<!ELEMENT	SequenceTypeData	%T_SequenceTypeData;>
<!ENTITY	 % T_SequenceTypeType	"(SequenceTypeData)*">

<!-- Members definition of Structure type: T_TermData -->
<!ELEMENT	SearchTerm		%T_string;>

<!-- Definition of Structure type: T_TermData -->
<!ENTITY	 % T_TermData	"(
 			SearchTerm
			)*">

<!-- Definition of List type: T_TermType -->
<!ELEMENT	TermData	%T_TermData;>
<!ENTITY	 % T_TermType	"(TermData)*">

<!-- Members definition of Structure type: T_OtherUrlData -->
<!ELEMENT	url		%T_string;>

<!-- Definition of Structure type: T_OtherUrlData -->
<!ENTITY	 % T_OtherUrlData	"(
 			url
			)*">

<!-- Definition of List type: T_OtherUrlType -->
<!ELEMENT	OtherUrlData	%T_OtherUrlData;>
<!ENTITY	 % T_OtherUrlType	"(OtherUrlData)*">

<!-- Members definition of Structure type: T_MaskingData -->
<!ELEMENT	tag		%T_string;>
<!ELEMENT	algorithm		%T_string;>
<!ELEMENT	options		%T_string;>

<!-- Definition of Structure type: T_MaskingData -->
<!ENTITY	 % T_MaskingData	"(
 			tag
			| algorithm
			| options
			)*">

<!-- Definition of List type: T_MaskingType -->
<!ELEMENT	MaskingData	%T_MaskingData;>
<!ENTITY	 % T_MaskingType	"(MaskingData)*">

<!-- Members definition of Structure type: T_ProjectData -->
<!ELEMENT	pid		%T_int;>

<!-- Definition of Structure type: T_ProjectData -->
<!ENTITY	 % T_ProjectData	"(
 			pid
			)*">

<!-- Definition of List type: T_ProjectType -->
<!ELEMENT	ProjectData	%T_ProjectData;>
<!ENTITY	 % T_ProjectType	"(ProjectData)*">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Name		%T_string;>
<!ELEMENT	Path		%T_string;>
<!ELEMENT	Title		%T_string;>
<!ELEMENT	LastUpdated		%T_date;>
<!ELEMENT	Description		%T_string;>
<!ELEMENT	TotalLength		%T_string;>
<!ELEMENT	MaxLength		%T_int;>
<!ELEMENT	NumSequences		%T_int;>
<!ELEMENT	Perc75		%T_int;>
<!ELEMENT	Perc50		%T_int;>
<!ELEMENT	Perc25		%T_int;>
<!ELEMENT	N50		%T_int;>
<!ELEMENT	Taxid		%T_int;>
<!ELEMENT	GenCollAssemblyName		%T_string;>
<!ELEMENT	EntrezDatabase		%T_string;>
<!ELEMENT	EntrezQuery		%T_string;>
<!ELEMENT	SourceDb		%T_SourceDbType;>
<!ELEMENT	SequenceType		%T_SequenceTypeType;>
<!ELEMENT	Term		%T_TermType;>
<!ELEMENT	OtherUrl		%T_OtherUrlType;>
<!ELEMENT	Masking		%T_MaskingType;>
<!ELEMENT	Project		%T_ProjectType;>
<!ELEMENT	GpipeBuild		%T_string;>
<!ELEMENT	WgsProject		%T_string;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			Name
			| Path
			| Title
			| LastUpdated
			| Description
			| TotalLength
			| MaxLength
			| NumSequences
			| Perc75
			| Perc50
			| Perc25
			| N50
			| Taxid
			| GenCollAssemblyName
			| EntrezDatabase
			| EntrezQuery
			| SourceDb
			| SequenceType
			| Term
			| OtherUrl
			| Masking
			| Project
			| GpipeBuild
			| WgsProject
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json <object/>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.blastdbinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_blastdbinfo.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="645844">
	<Name>Felis catus</Name>
	<Path>SNP/cat_9685</Path>
	<Title>cat_9685</Title>
	<LastUpdated>2011/01/14 00:00</LastUpdated>
	<Description>dbSNP cat_9685 blast database</Description>
	<TotalLength>200357206</TotalLength>
	<MaxLength>1003</MaxLength>
	<NumSequences>327037</NumSequences>
	<Perc75>757</Perc75>
	<Perc50>588</Perc50>
	<Perc25>402</Perc25>
	<N50>0</N50>
	<Taxid>9685</Taxid>
	<GenCollAssemblyName></GenCollAssemblyName>
	<EntrezDatabase></EntrezDatabase>
	<EntrezQuery></EntrezQuery>
	<SourceDb>
		<SourceDbData>
			<SrcDb>dbSNP</SrcDb>
		</SourceDbData>
	</SourceDb>
	<SequenceType>
		<SequenceTypeData>
			<SeqType>OtherDNA</SeqType>
			<SeqStrategy></SeqStrategy>
		</SequenceTypeData>
	</SequenceType>
	<Term>
		<TermData>
			<SearchTerm>variation</SearchTerm>
		</TermData>
		<TermData>
			<SearchTerm>SNP</SearchTerm>
		</TermData>
		<TermData>
			<SearchTerm>polymorphism</SearchTerm>
		</TermData>
		<TermData>
			<SearchTerm>dbSNP</SearchTerm>
		</TermData>
	</Term>
	<OtherUrl>
	</OtherUrl>
	<Masking>
	</Masking>
	<Project>
	</Project>
	<GpipeBuild></GpipeBuild>
	<WgsProject></WgsProject>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
