=== Klortho/Eutils-JSON/samples/eSummary_genome.dtd
<!-- $Id: eSummary_genome.dtd 342479 2011-10-27 20:49:57Z fedorov $ -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!-- IDXCODEBLOCK_START_ELEMENTS -->
<!ELEMENT AssemblyID	 (#PCDATA)>
<!ATTLIST AssemblyID	 weight CDATA #IMPLIED>
<!ELEMENT Assembly_Accession	 (#PCDATA)>
<!ATTLIST Assembly_Accession	 weight CDATA #IMPLIED>
<!ELEMENT Assembly_Name	 (#PCDATA)>
<!ATTLIST Assembly_Name	 weight CDATA #IMPLIED>
<!ELEMENT Biological_Property	 (#PCDATA)>
<!ATTLIST Biological_Property	 weight CDATA #IMPLIED>
<!ELEMENT ClusterID	 (#PCDATA)>
<!ATTLIST ClusterID	 weight CDATA #IMPLIED>
<!ELEMENT CreateDate	 (#PCDATA)>
<!ATTLIST CreateDate	 weight CDATA #IMPLIED>
<!ELEMENT Defline	 (#PCDATA)>
<!ATTLIST Defline	 weight CDATA #IMPLIED>
<!ELEMENT Description	 (#PCDATA)>
<!ATTLIST Description	 weight CDATA #IMPLIED>
<!ELEMENT Filter	 (#PCDATA)>
<!ATTLIST Filter	 weight CDATA #IMPLIED>
<!ELEMENT GeneID	 (#PCDATA)>
<!ATTLIST GeneID	 weight CDATA #IMPLIED>
<!ELEMENT Locus	 (#PCDATA)>
<!ATTLIST Locus	 weight CDATA #IMPLIED>
<!ELEMENT Locus_tag	 (#PCDATA)>
<!ATTLIST Locus_tag	 weight CDATA #IMPLIED>
<!ELEMENT Organism	 (#PCDATA)>
<!ATTLIST Organism	 weight CDATA #IMPLIED>
<!ELEMENT PmId	 (#PCDATA)>
<!ATTLIST PmId	 weight CDATA #IMPLIED>
<!ELEMENT ProjectID	 (#PCDATA)>
<!ATTLIST ProjectID	 weight CDATA #IMPLIED>
<!ELEMENT Project_Accession	 (#PCDATA)>
<!ATTLIST Project_Accession	 weight CDATA #IMPLIED>
<!ELEMENT Properties	 (#PCDATA)>
<!ATTLIST Properties	 weight CDATA #IMPLIED>
<!ELEMENT ProteinGI	 (#PCDATA)>
<!ATTLIST ProteinGI	 weight CDATA #IMPLIED>
<!ELEMENT Protein_Accession	 (#PCDATA)>
<!ATTLIST Protein_Accession	 weight CDATA #IMPLIED>
<!ELEMENT Protein_Name	 (#PCDATA)>
<!ATTLIST Protein_Name	 weight CDATA #IMPLIED>
<!ELEMENT RepliconGI	 (#PCDATA)>
<!ATTLIST RepliconGI	 weight CDATA #IMPLIED>
<!ELEMENT Replicon_Accession	 (#PCDATA)>
<!ATTLIST Replicon_Accession	 weight CDATA #IMPLIED>
<!ELEMENT Replicon_Name	 (#PCDATA)>
<!ATTLIST Replicon_Name	 weight CDATA #IMPLIED>
<!ELEMENT Status	 (#PCDATA)>
<!ATTLIST Status	 weight CDATA #IMPLIED>
<!ELEMENT TaxId	 (#PCDATA)>
<!ELEMENT Uid	 (#PCDATA)>
<!ATTLIST Uid	 weight CDATA #IMPLIED>
<!ELEMENT WGS_Prefix	 (#PCDATA)>
<!ATTLIST WGS_Prefix	 weight CDATA #IMPLIED>
<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">
<!ENTITY	 % T_date		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Organism_Name		%T_string;>
<!ELEMENT	Organism_Kingdom		%T_string;>
<!-- Already defined ...
<!ELEMENT	Defline		%T_string;>
 ... Already defined -->
<!-- Already defined ...
<!ELEMENT	ProjectID		%T_int;>
 ... Already defined -->
<!-- Already defined ...
<!ELEMENT	Project_Accession		%T_string;>
 ... Already defined -->
<!-- Already defined ...
<!ELEMENT	Status		%T_string;>
 ... Already defined -->
<!ELEMENT	Number_of_Chromosomes		%T_string;>
<!ELEMENT	Number_of_Plasmids		%T_string;>
<!ELEMENT	Number_of_Organelles		%T_string;>
<!-- Already defined ...
<!ELEMENT	Assembly_Name		%T_string;>
 ... Already defined -->
<!-- Already defined ...
<!ELEMENT	Assembly_Accession		%T_string;>
 ... Already defined -->
<!-- Already defined ...
<!ELEMENT	AssemblyID		%T_int;>
 ... Already defined -->
<!ELEMENT	Create_Date		%T_date;>
<!ELEMENT	Options		%T_string;>
<!--~~ <Weight>
~~json <number/>
~~-->
<!ELEMENT	Weight		%T_int;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			Organism_Name
			| Organism_Kingdom
			| Defline
			| ProjectID
			| Project_Accession
			| Status
			| Number_of_Chromosomes
			| Number_of_Plasmids
			| Number_of_Organelles
			| Assembly_Name
			| Assembly_Accession
			| AssemblyID
			| Create_Date
			| Options
			| Weight
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!ELEMENT Warning (Otherdb)+>
<!ELEMENT Otherdb   EMPTY>
<!ATTLIST Otherdb
  db    CDATA #IMPLIED
  term  CDATA #IMPLIED
  uid   CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json <object/>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary | Warning)*>
<!ATTLIST DocumentSummarySet status CDATA #IMPLIED>
<!--~~ <eSummaryResult>
~~ tags root
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.genome.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_genome.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="2640">
	<Organism_Name>Maylandia zebra</Organism_Name>
	<Organism_Kingdom>Eukaryotes</Organism_Kingdom>
	<Organism_Group></Organism_Group>
	<Organism_Subgroup>Fishes</Organism_Subgroup>
	<Defline>The zebra mbuna is a freshwater cichlid fish found in lakes in Malawi, Mozambique, and Tanzania.</Defline>
	<ProjectID>43325</ProjectID>
	<Project_Accession>PRJNA43325</Project_Accession>
	<Status>Draft</Status>
	<Number_of_Chromosomes>0</Number_of_Chromosomes>
	<Number_of_Plasmids>0</Number_of_Plasmids>
	<Number_of_Organelles>0</Number_of_Organelles>
	<Assembly_Name>MetZeb1.1</Assembly_Name>
	<Assembly_Accession>GCA_000238955.2</Assembly_Accession>
	<AssemblyID>398768</AssemblyID>
	<Create_Date>2010/01/01 00:00</Create_Date>
	<Options></Options>
	<Weight>0</Weight>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
