=== Klortho/Eutils-JSON/samples/eSummary_epigenomics.dtd
<!-- DocSum DTD for epigenomics database -->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">
<!ENTITY	 % T_date		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Title		%T_string;>
<!ELEMENT	Summary		%T_string;>
<!ELEMENT	DocType		%T_string;>
<!ELEMENT	TaxId		%T_int;>
<!ELEMENT	GeneId		%T_int;>
<!ELEMENT	UpdateDate		%T_date;>
<!ELEMENT	CreateDate		%T_date;>
<!ELEMENT	Accession		%T_string;>
<!ELEMENT	DocStatus		%T_int;>
<!ELEMENT	ReplacedById		%T_int;>
<!ELEMENT	RetireDate		%T_date;>
<!ELEMENT	RetireComment		%T_string;>

<!-- Definition of Structure type: T_DocSum -->
<!ENTITY	 % T_DocSum	"(
 			Title
			| Summary
			| DocType
			| TaxId
			| GeneId
			| UpdateDate
			| CreateDate
			| Accession
			| DocStatus
			| ReplacedById
			| RetireDate
			| RetireComment
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.epigenomics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_epigenomics.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="16796">
	<Title>H3K4me1 - Human stem cell, iPS DF 6.9 cell line, foreskin, undifferentiated, passage 33</Title>
	<Summary>Histone modification H3K4me1 assayed by ChIP-seq in Homo sapiens, iPS DF 6.9 cell line, induced pluripotent stem cell, derived from newborn foreskin fibroblast (Cat# CRL-2097TM). Clone 6 sublcone 9. Data from the Roadmap Epigenomics project.</Summary>
	<DocType>experiment</DocType>
	<TaxId>9606</TaxId>
	<GeneId>0</GeneId>
	<UpdateDate>2012/10/31 00:00</UpdateDate>
	<CreateDate>2011/12/07 00:00</CreateDate>
	<Accession>ESX000004137</Accession>
	<DocStatus>3</DocStatus>
	<ReplacedById>0</ReplacedById>
	<RetireDate>1/01/01 00:00</RetireDate>
	<RetireComment></RetireComment>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
