=== Klortho/Eutils-JSON/samples/eSummary_omia.dtd
<!-- DocSum DTD for omia database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">

<!-- Members definition of Structure type: T_MP -->
<!ELEMENT	MP_ID		%T_string;>
<!ELEMENT	MP_Name		%T_string;>

<!-- Definition of Structure type: T_MP -->
<!--~~ <MP>
~~json <object/>
~~-->
<!ENTITY	 % T_MP	"(
 			MP_ID
			| MP_Name
			)*">

<!-- Definition of List type: T_MPListType -->
<!ELEMENT	MP	%T_MP;>
<!ENTITY	 % T_MPListType	"(MP)*">

<!-- Definition of List type: T_StringList -->
<!ELEMENT	string	%T_string;>
<!ENTITY	 % T_StringList	"(string)*">

<!-- Members definition of Structure type: T_Gene -->
<!ELEMENT	Gene_ID		%T_string;>
<!ELEMENT	Gene_Name		%T_string;>

<!-- Definition of Structure type: T_Gene -->
<!--~~ <Gene>
~~json <object/>
~~-->
<!ENTITY	 % T_Gene	"(
 			Gene_ID
			| Gene_Name
			)*">

<!-- Definition of List type: T_GeneListType -->
<!ELEMENT	Gene	%T_Gene;>
<!ENTITY	 % T_GeneListType	"(Gene)*">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Definition of List type: T_IntList -->
<!--~~ <int>
~~json <number/>
~~-->
<!ELEMENT	int	%T_int;>
<!ENTITY	 % T_IntList	"(int)*">

<!-- Members definition of Structure type: T_Reference -->
<!ELEMENT	Title		%T_string;>
<!ELEMENT	Journal		%T_string;>
<!ELEMENT	Volume		%T_string;>
<!ELEMENT	Pages		%T_string;>

<!--~~ <Year>
~~json <number/>
~~-->
<!ELEMENT	Year		%T_int;>

<!ELEMENT	Publisher		%T_string;>
<!ELEMENT	Publish_Place		%T_string;>
<!ELEMENT	Author_List		%T_StringList;>

<!--~~ <PubMed_UID>
~~json <number/>
~~-->
<!ELEMENT	PubMed_UID		%T_int;>

<!-- Definition of Structure type: T_Reference -->
<!--~~ <Reference>
~~json <object/>
~~-->
<!ENTITY	 % T_Reference	"(
 			Title
			| Journal
			| Volume
			| Pages
			| Year
			| Publisher
			| Publish_Place
			| Author_List
			| PubMed_UID
			)*">

<!-- Definition of List type: T_ReferenceListType -->
<!ELEMENT	Reference	%T_Reference;>
<!ENTITY	 % T_ReferenceListType	"(Reference)*">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Phenotype		%T_string;>
<!ELEMENT	Phenotype_Summary		%T_string;>
<!ELEMENT	OMIA_ID		%T_string;>
<!ELEMENT	MP_List		%T_MPListType;>
<!ELEMENT	Species_Phenotype_Name		%T_string;>
<!ELEMENT	Species_Phenotype_Summary		%T_string;>
<!ELEMENT	Across_Species_Synonym_List		%T_StringList;>
<!ELEMENT	Taxonomy_ID		%T_string;>
<!ELEMENT	Sci_Name		%T_string;>
<!ELEMENT	Common_Name		%T_string;>
<!ELEMENT	Breed		%T_StringList;>
<!ELEMENT	Clinical_Feature		%T_string;>
<!ELEMENT	Genetic_Test		%T_string;>
<!ELEMENT	Molecular_Genetics		%T_string;>
<!ELEMENT	Pathology		%T_string;>
<!ELEMENT	Prevalence		%T_string;>
<!ELEMENT	Gene_List		%T_GeneListType;>
<!ELEMENT	Computed_Gene_List		%T_GeneListType;>
<!ELEMENT	OMIM_ID		%T_IntList;>
<!ELEMENT	Inheritance		%T_string;>
<!ELEMENT	Inherit_Text		%T_string;>
<!ELEMENT	Reference_List		%T_ReferenceListType;>
<!ELEMENT	PubMed_List		%T_IntList;>
<!ELEMENT	Curation_State		%T_string;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			Phenotype
			| Phenotype_Summary
			| OMIA_ID
			| MP_List
			| Species_Phenotype_Name
			| Species_Phenotype_Summary
			| Across_Species_Synonym_List
			| Taxonomy_ID
			| Sci_Name
			| Common_Name
			| Breed
			| Clinical_Feature
			| Genetic_Test
			| Molecular_Genetics
			| Pathology
			| Prevalence
			| Gene_List
			| Computed_Gene_List
			| OMIM_ID
			| Inheritance
			| Inherit_Text
			| Reference_List
			| PubMed_List
			| Curation_State
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json 
  <object name='"result"'>
    <array name='"uids"' select='DocumentSummary/@uid'/>
    <members select='DocumentSummary'/>
  </object>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ json <member/>
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.omia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_omia.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="2615">
	<Phenotype>Epidermolysis bullosa, dystrophic</Phenotype>
	<Phenotype_Summary>Blisters on the outer layer of skin.</Phenotype_Summary>
	<OMIA_ID>341</OMIA_ID>
	<MP_List>
	</MP_List>
	<Species_Phenotype_Name></Species_Phenotype_Name>
	<Species_Phenotype_Summary></Species_Phenotype_Summary>
	<Across_Species_Synonym_List>
	</Across_Species_Synonym_List>
	<Taxonomy_ID>9685</Taxonomy_ID>
	<Sci_Name>Felis catus</Sci_Name>
	<Common_Name>domestic cat</Common_Name>
	<Breed>
	</Breed>
	<Clinical_Feature></Clinical_Feature>
	<Genetic_Test></Genetic_Test>
	<Molecular_Genetics></Molecular_Genetics>
	<Pathology></Pathology>
	<Prevalence></Prevalence>
	<Gene_List>
	</Gene_List>
	<Computed_Gene_List>
	</Computed_Gene_List>
	<OMIM_ID>
		<int>131705</int>
		<int>131750</int>
		<int>131950</int>
		<int>132000</int>
		<int>226500</int>
		<int>226600</int>
	</OMIM_ID>
	<Inheritance></Inheritance>
	<Inherit_Text></Inherit_Text>
	<Reference_List>
	</Reference_List>
	<PubMed_List>
		<int>10568446</int>
	</PubMed_List>
	<Curation_State></Curation_State>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
