=== Klortho/Eutils-JSON/samples/eSummary_snp.dtd
<!-- DocSum DTD for snp database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_int		"(#PCDATA)">
<!ENTITY	 % T_string		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!--~~ <SNP_ID>
~~json <number/>
~~-->
<!ELEMENT	SNP_ID		%T_int;>

<!ELEMENT	Organism		%T_string;>
<!ELEMENT	ALLELE_ORIGIN		%T_string;>
<!ELEMENT	GLOBAL_MAF		%T_string;>
<!ELEMENT	GLOBAL_POPULATION		%T_string;>

<!--~~ <GLOBAL_SAMPLESIZE>
~~json <number/>
~~-->
<!ELEMENT	GLOBAL_SAMPLESIZE		%T_int;>

<!ELEMENT	SUSPECTED		%T_string;>
<!ELEMENT	CLINICAL_SIGNIFICANCE		%T_string;>
<!ELEMENT	GENE		%T_string;>

<!--~~ <LOCUS_ID>
~~json <number/>
~~-->
<!ELEMENT	LOCUS_ID		%T_int;>

<!ELEMENT	ACC		%T_string;>
<!ELEMENT	CHR		%T_string;>

<!--~~ <WEIGHT>
~~json <number/>
~~-->
<!ELEMENT	WEIGHT		%T_int;>

<!ELEMENT	HANDLE		%T_string;>
<!ELEMENT	FXN_CLASS		%T_string;>
<!ELEMENT	VALIDATED		%T_string;>
<!ELEMENT	GTYPE		%T_string;>
<!ELEMENT	NONREF		%T_string;>
<!ELEMENT	DOCSUM		%T_string;>

<!--~~ <HET>
~~json <number/>
~~-->
<!ELEMENT	HET		%T_int;>

<!--~~ <SRATE>
~~json <number/>
~~-->
<!ELEMENT	SRATE		%T_int;>

<!--~~ <TAX_ID>
~~json <number/>
~~-->
<!ELEMENT	TAX_ID		%T_int;>

<!ELEMENT	CHRRPT		%T_string;>

<!--~~ <ORIG_BUILD>
~~json <number/>
~~-->
<!ELEMENT	ORIG_BUILD		%T_int;>

<!--~~ <UPD_BUILD>
~~json <number/>
~~-->
<!ELEMENT	UPD_BUILD		%T_int;>

<!ELEMENT	CREATEDATE		%T_string;>
<!ELEMENT	UPDATEDATE		%T_string;>
<!ELEMENT	POP_CLASS		%T_string;>
<!ELEMENT	METHOD_CLASS		%T_string;>
<!ELEMENT	SNP3D		%T_string;>
<!ELEMENT	LINKOUT		%T_string;>

<!--~~ <SS>
~~json <number/>
~~-->
<!ELEMENT	SS		%T_int;>

<!ELEMENT	LOCSNPID		%T_string;>
<!ELEMENT	ALLELE		%T_string;>
<!ELEMENT	SNP_CLASS		%T_string;>
<!ELEMENT	CHRPOS		%T_string;>
<!ELEMENT	CONTIGPOS		%T_string;>
<!ELEMENT	TEXT		%T_string;>
<!ELEMENT	LOOKUP		%T_string;>

<!--~~ <SORT_PRIORITY>
~~json <number/>
~~-->
<!ELEMENT	SORT_PRIORITY		%T_int;>

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			SNP_ID
			| Organism
			| ALLELE_ORIGIN
			| GLOBAL_MAF
			| GLOBAL_POPULATION
			| GLOBAL_SAMPLESIZE
			| SUSPECTED
			| CLINICAL_SIGNIFICANCE
			| GENE
			| LOCUS_ID
			| ACC
			| CHR
			| WEIGHT
			| HANDLE
			| FXN_CLASS
			| VALIDATED
			| GTYPE
			| NONREF
			| DOCSUM
			| HET
			| SRATE
			| TAX_ID
			| CHRRPT
			| ORIG_BUILD
			| UPD_BUILD
			| CREATEDATE
			| UPDATEDATE
			| POP_CLASS
			| METHOD_CLASS
			| SNP3D
			| LINKOUT
			| SS
			| LOCSNPID
			| ALLELE
			| SNP_CLASS
			| CHRPOS
			| CONTIGPOS
			| TEXT
			| LOOKUP
			| SORT_PRIORITY
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json <object/>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.snp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_snp.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="206676795">
	<SNP_ID>206676795</SNP_ID>
	<Organism></Organism>
	<ALLELE_ORIGIN></ALLELE_ORIGIN>
	<GLOBAL_MAF></GLOBAL_MAF>
	<GLOBAL_POPULATION></GLOBAL_POPULATION>
	<GLOBAL_SAMPLESIZE>0</GLOBAL_SAMPLESIZE>
	<SUSPECTED></SUSPECTED>
	<CLINICAL_SIGNIFICANCE></CLINICAL_SIGNIFICANCE>
	<GENE>CG2650,per</GENE>
	<LOCUS_ID>31251</LOCUS_ID>
	<ACC>NC_004354.3,NM_080317.2,NM_130660.1</ACC>
	<CHR>X</CHR>
	<WEIGHT>1</WEIGHT>
	<HANDLE>BCM-HGSC-SUB</HANDLE>
	<FXN_CLASS>downstream-variant-500B,utr-variant-3-prime</FXN_CLASS>
	<VALIDATED>no-info</VALIDATED>
	<GTYPE></GTYPE>
	<NONREF>false</NONREF>
	<DOCSUM>SEQ=ATATTAAGTGAATTGAAAACTAGAG[A/T]GGGTTCGAACATCGAACCACCCTTC|GENE=CG2650:31252,per:31251</DOCSUM>
	<HET>0</HET>
	<SRATE>0</SRATE>
	<TAX_ID>7227</TAX_ID>
	<CHRRPT>206676795|2|0|1|1|1|X|NC_004354.3|2586711|2586712|CG2650,per| | | |0|0|1|137|137</CHRRPT>
	<ORIG_BUILD>137</ORIG_BUILD>
	<UPD_BUILD>137</UPD_BUILD>
	<CREATEDATE>2012-06-19 14:19</CREATEDATE>
	<UPDATEDATE>2012-06-19 14:19</UPDATEDATE>
	<POP_CLASS></POP_CLASS>
	<METHOD_CLASS>sequence</METHOD_CLASS>
	<SNP3D></SNP3D>
	<LINKOUT></LINKOUT>
	<SS>274660485</SS>
	<LOCSNPID>DGRP_SM159-4522465</LOCSNPID>
	<ALLELE>W</ALLELE>
	<SNP_CLASS>snp</SNP_CLASS>
	<CHRPOS>X:2586712</CHRPOS>
	<CONTIGPOS>NC_004354.3:2586712</CONTIGPOS>
	<TEXT></TEXT>
	<LOOKUP>ds_bin_chX.bin:940284143</LOOKUP>
	<SORT_PRIORITY>0</SORT_PRIORITY>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
