=== Klortho/Eutils-JSON/samples/eSummary_gene.dtd
<!-- DocSum DTD for gene database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Definition of List type: T_MimListType -->

<!--~~ <int>
~~json <number/>
~~-->
<!ELEMENT	int	%T_int;>

<!ENTITY	 % T_MimListType	"(int)*">

<!-- Members definition of Structure type: T_GenomicInfoType -->
<!ELEMENT	ChrLoc		%T_string;>
<!ELEMENT	ChrAccVer		%T_string;>

<!--~~ <ChrStart>
~~json <number/>
~~-->
<!ELEMENT	ChrStart		%T_int;>

<!--~~ <ChrStop>
~~json <number/>
~~-->
<!ELEMENT	ChrStop		%T_int;>

<!--~~ <ExonCount>
~~json <number/>
~~-->
<!ELEMENT	ExonCount		%T_int;>

<!-- Definition of Structure type: T_GenomicInfoType -->
<!--~~ <GenomicInfoType>
~~json <object/>
~~-->
<!ENTITY	 % T_GenomicInfoType	"(
 			ChrLoc
			| ChrAccVer
			| ChrStart
			| ChrStop
			| ExonCount
			)*">

<!-- Definition of List type: T_GenomicInfoListType -->
<!ELEMENT	GenomicInfoType	%T_GenomicInfoType;>
<!ENTITY	 % T_GenomicInfoListType	"(GenomicInfoType)*">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	Name		%T_string;>
<!ELEMENT	Description		%T_string;>
<!ELEMENT	Orgname		%T_string;>

<!--~~ <Status>
~~json <number/>
~~-->
<!ELEMENT	Status		%T_int;>

<!--~~ <CurrentID>
~~json <number/>
~~-->
<!ELEMENT	CurrentID		%T_int;>

<!ELEMENT	Chromosome		%T_string;>
<!ELEMENT	GeneticSource		%T_string;>
<!ELEMENT	MapLocation		%T_string;>
<!ELEMENT	OtherAliases		%T_string;>
<!ELEMENT	OtherDesignations		%T_string;>
<!ELEMENT	NomenclatureSymbol		%T_string;>
<!ELEMENT	NomenclatureName		%T_string;>
<!ELEMENT	NomenclatureStatus		%T_string;>

<!--~~ <TaxID>
~~json <number/>
~~-->
<!ELEMENT	TaxID		%T_int;>

<!ELEMENT	Mim		%T_MimListType;>
<!ELEMENT	GenomicInfo		%T_GenomicInfoListType;>

<!--~~ <GeneWeight>
~~json <number/>
~~-->
<!ELEMENT	GeneWeight		%T_int;>

<!ELEMENT	Summary		%T_string;>
<!ELEMENT	ChrSort		%T_string;>
<!-- Already defined ...
<!ELEMENT	ChrStart		%T_int;>
 ... Already defined -->

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			Name
			| Description
			| Orgname
			| Status
			| CurrentID
			| Chromosome
			| GeneticSource
			| MapLocation
			| OtherAliases
			| OtherDesignations
			| NomenclatureSymbol
			| NomenclatureName
			| NomenclatureStatus
			| TaxID
			| Mim
			| GenomicInfo
			| GeneWeight
			| Summary
			| ChrSort
			| ChrStart
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json <object/>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ tags root
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.gene.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_gene.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="21803">
	<Name>Tgfb1</Name>
	<Description>transforming growth factor, beta 1</Description>
	<Orgname>Mus musculus</Orgname>
	<Status>0</Status>
	<CurrentID>0</CurrentID>
	<Chromosome>7</Chromosome>
	<GeneticSource>genomic</GeneticSource>
	<MapLocation>7 6.5 cM</MapLocation>
	<OtherAliases>TGF-beta1, TGFbeta1, Tgfb, Tgfb-1</OtherAliases>
	<OtherDesignations>TGF-beta 1|TGF-beta-1|regulatory protein|transforming growth factor beta-1|transforming growth factor-beta 1</OtherDesignations>
	<NomenclatureSymbol>Tgfb1</NomenclatureSymbol>
	<NomenclatureName>transforming growth factor, beta 1</NomenclatureName>
	<NomenclatureStatus>Official</NomenclatureStatus>
	<TaxID>10090</TaxID>
	<Mim>
	</Mim>
	<GenomicInfo>
		<GenomicInfoType>
			<ChrLoc>7</ChrLoc>
			<ChrAccVer>NC_000073.6</ChrAccVer>
			<ChrStart>25687001</ChrStart>
			<ChrStop>25704995</ChrStop>
			<ExonCount>7</ExonCount>
		</GenomicInfoType>
	</GenomicInfo>
	<GeneWeight>204825</GeneWeight>
	<Summary></Summary>
	<ChrSort>07</ChrSort>
	<ChrStart>25687001</ChrStart>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
