=== Klortho/Eutils-JSON/samples/eSummary_pmc.dtd
<!-- DocSum DTD for pmc database -->

<!--~~ !dtd
~~json 
    <json type='esummary' version='0.3'>
      <config lcnames='true'/>
    </json>
~~-->

<!ENTITY	 % T_string		"(#PCDATA)">

<!-- Definition of Enumeration type: T_AuthorType -->
<!ENTITY	 % T_AuthorType		"(#PCDATA)">

<!-- Members definition of Structure type: T_Author -->
<!ELEMENT	Name		%T_string;>
<!ELEMENT	AuthType		%T_AuthorType;>

<!-- Definition of Structure type: T_Author -->
<!--~~ <Author>
~~json <object/>
~~-->
<!ENTITY	 % T_Author	"(
 			Name
			| AuthType
			)*">

<!-- Definition of List type: T_AuthorList -->
<!ELEMENT	Author	%T_Author;>
<!ENTITY	 % T_AuthorList	"(Author)*">

<!-- Members definition of Structure type: T_ArticleId -->
<!ELEMENT	IdType		%T_string;>
<!ELEMENT	Value		%T_string;>

<!-- Definition of Structure type: T_ArticleId -->
<!--~~ <ArticleId>
~~json <object/>
~~-->
<!ENTITY	 % T_ArticleId	"(
 			IdType
			| Value
			)*">

<!-- Definition of List type: T_ArticleIdList -->
<!ELEMENT	ArticleId	%T_ArticleId;>
<!ENTITY	 % T_ArticleIdList	"(ArticleId)*">
<!ENTITY	 % T_date		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT	PubDate		%T_string;>
<!ELEMENT	EPubDate		%T_string;>
<!ELEMENT	Source		%T_string;>
<!ELEMENT	Authors		%T_AuthorList;>
<!ELEMENT	Title		%T_string;>
<!ELEMENT	Volume		%T_string;>
<!ELEMENT	Issue		%T_string;>
<!ELEMENT	Pages		%T_string;>
<!ELEMENT	ArticleIds		%T_ArticleIdList;>
<!ELEMENT	FullJournalName		%T_string;>
<!ELEMENT	SortDate		%T_date;>
<!ELEMENT	PmcLiveDate		%T_date;>
<!ELEMENT error (#PCDATA) >

<!-- Definition of Structure type: T_DocSum -->
<!--~~ <DocumentSummary>
~~json <object name='@uid'/>
~~-->
<!ENTITY	 % T_DocSum	"(
 			PubDate
			| EPubDate
			| Source
			| Authors
			| Title
			| Volume
			| Issue
			| Pages
			| ArticleIds
			| FullJournalName
			| SortDate
			| PmcLiveDate
			| error
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!--~~ <DocumentSummarySet>
~~json 
  <object name='"result"'>
    <array name='"uids"' select='DocumentSummary/@uid'/>
    <members select='DocumentSummary'/>
  </object>
~~-->
<!ELEMENT DocumentSummarySet (DocumentSummary*)>
<!ATTLIST DocumentSummarySet status CDATA #REQUIRED>

<!--~~ <eSummaryResult>
~~ json <member/>
~~-->
<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.pmc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_pmc.dtd">
<eSummaryResult>
<DocumentSummarySet status="OK">
<DocumentSummary uid="254085">
	<PubDate>1987 Apr</PubDate>
	<EPubDate></EPubDate>
	<Source>J Virol</Source>
	<Authors>
		<Author>
			<Name>Davidson D</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
		<Author>
			<Name>Hassell JA</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
	</Authors>
	<Title>Overproduction of polyomavirus middle T antigen in mammalian cells through the use of an adenovirus vector.</Title>
	<Volume>61</Volume>
	<Issue>4</Issue>
	<Pages>1226-1239</Pages>
	<ArticleIds>
		<ArticleId>
			<IdType>pmid</IdType>
			<Value>3029418</Value>
		</ArticleId>
		<ArticleId>
			<IdType>pmcid</IdType>
			<Value>PMC254085</Value>
		</ArticleId>
	</ArticleIds>
	<FullJournalName>Journal of Virology</FullJournalName>
	<SortDate>1987/04/01 00:00</SortDate>
	<PmcLiveDate>2003/12/01 00:00</PmcLiveDate>
</DocumentSummary>
<DocumentSummary uid="1">
<error>cannot get document summary</error>
</DocumentSummary>

<DocumentSummary uid="14900">
	<PubDate>2000 Jun</PubDate>
	<EPubDate></EPubDate>
	<Source>Mol Biol Cell</Source>
	<Authors>
		<Author>
			<Name>Temesvari L</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
		<Author>
			<Name>Zhang L</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
		<Author>
			<Name>Fodera B</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
		<Author>
			<Name>Janssen KP</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
		<Author>
			<Name>Schleicher M</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
		<Author>
			<Name>Cardelli JA</Name>
			<AuthType>
				Author
			</AuthType>
		</Author>
	</Authors>
	<Title>Inactivation of lmpA, Encoding a LIMPII-related Endosomal Protein, Suppresses the Internalization and Endosomal Trafficking Defects in Profilin-null Mutants</Title>
	<Volume>11</Volume>
	<Issue>6</Issue>
	<Pages>2019-2031</Pages>
	<ArticleIds>
		<ArticleId>
			<IdType>pmid</IdType>
			<Value>10848626</Value>
		</ArticleId>
		<ArticleId>
			<IdType>pmcid</IdType>
			<Value>PMC14900</Value>
		</ArticleId>
	</ArticleIds>
	<FullJournalName>Molecular Biology of the Cell</FullJournalName>
	<SortDate>2000/06/01 00:00</SortDate>
	<PmcLiveDate>2001/03/07 00:00</PmcLiveDate>
</DocumentSummary>

</DocumentSummarySet>
</eSummaryResult>
