=== Klortho/Eutils-JSON/daz/eSummary_nucgss.dtd
<!-- DocSum DTD for all sequence databases -->

<!ENTITY	 % T_string		"(#PCDATA)">
<!ENTITY	 % T_int		"(#PCDATA)">

<!-- Members definition of Structure type: T_DocSum -->
<!ELEMENT   error       %T_string;>
<!ELEMENT	Caption		%T_string;>
<!ELEMENT	Title		%T_string;>
<!ELEMENT	Extra		%T_string;>
<!ELEMENT	Gi		%T_int;>
<!ELEMENT	CreateDate		%T_string;>
<!ELEMENT	UpdateDate		%T_string;>
<!ELEMENT	Flags		%T_int;>
<!ELEMENT	TaxId		%T_int;>
<!ELEMENT	Slen		%T_int;>
<!ELEMENT   Statistics  (Stat)+>
<!ELEMENT   Stat        EMPTY>
<!ATTLIST   Stat
  count     CDATA       #IMPLIED
  subtype   CDATA       #IMPLIED
  value     CDATA       #IMPLIED
  source    CDATA       #IMPLIED
  type      CDATA       #IMPLIED>
<!ELEMENT	Biomol		%T_string;>
<!-- Until docsuminfo with fixed Biomol field is propagated, we'll need this spelling as well: -->
<!ELEMENT	BioMol		%T_string;>
<!ELEMENT	MolType		%T_string;>
<!ELEMENT	Topology	%T_string;>
<!ELEMENT	SourceDb	%T_string;>
<!ELEMENT	SegSetSize	%T_int;>
<!ELEMENT	ProjectId	%T_int;>
<!ELEMENT	Genome		%T_string;>
<!ELEMENT	SubType		%T_string;>
<!ELEMENT	SubName		%T_string;>
<!ELEMENT	AssemblyGi	%T_int;>
<!ELEMENT	AssemblyAcc	%T_string;>
<!ELEMENT	Tech		%T_string;>
<!ELEMENT	Completeness	%T_string;>
<!ELEMENT	GeneticCode	%T_string;>
<!ELEMENT	Strand		%T_string;>
<!ELEMENT	Organism	%T_string;>
<!ELEMENT   AccessionVersion %T_string;>
<!ELEMENT   Properties  %T_string;>
<!ATTLIST   Properties
  na        CDATA       #IMPLIED
  aa        CDATA       #IMPLIED
  est       CDATA       #IMPLIED
  gss       CDATA       #IMPLIED
  trace     CDATA       #IMPLIED
  qual      CDATA       #IMPLIED
  genome    CDATA       #IMPLIED
  popset    CDATA       #IMPLIED>
<!ELEMENT   Comment     %T_string;>
<!ELEMENT   Status      %T_string;>
<!ELEMENT   OSLT        %T_string;>
<!ATTLIST   OSLT
  indexed   CDATA       #IMPLIED>
<!ELEMENT   ReplacedBy  %T_string;>
<!ELEMENT   IdGiClass   EMPTY>
<!ATTLIST IdGiClass
  defdiv    CDATA       #IMPLIED
  extfeatmask CDATA     #IMPLIED
  gi_state  CDATA       #IMPLIED
  length    CDATA       #IMPLIED
  mol       CDATA       #IMPLIED
  owner     CDATA       #IMPLIED
  owner_name CDATA      #IMPLIED
  repr      CDATA       #IMPLIED
  sat       CDATA       #IMPLIED
  sat_key   CDATA       #IMPLIED
  sat_name  CDATA       #IMPLIED>
<!-- PopSet fields -->
<!ELEMENT   SetType     %T_string;>
<!-- Genome fields -->
<!ELEMENT   Meta        (#PCDATA)>
<!ELEMENT   Refseq_accession    %T_string;>
<!ELEMENT   GenBank_accession   %T_string;>
<!ELEMENT   PubMedIds           %T_string;>
<!ELEMENT   Sequencing_centers  %T_string;>
<!ELEMENT   Reviewed_status     %T_string;>
<!ELEMENT   Subtype             %T_string;>
<!ELEMENT   GenomeExtra         %T_string;>
<!ELEMENT   MoleculeType        %T_string;>
<!ELEMENT   DNA_length          %T_string;>
<!ELEMENT   Protein_count       %T_string;>
<!ELEMENT   RNA_count           %T_string;>
<!ELEMENT   Gene_count          %T_string;>
<!ELEMENT   Total_count         %T_string;>
<!ELEMENT   GC_content          %T_string;>
<!ELEMENT   ProjectID           %T_string;>
<!ELEMENT   ViewerIdx           %T_string;>
<!ELEMENT   TraceGi             %T_string;>
<!ELEMENT   ContigNum           %T_string;>
<!ELEMENT   NeighborNum         %T_string;>
<!ELEMENT   Replicon_type       %T_string;>
<!ELEMENT   Replicon_name       %T_string;>
<!ELEMENT   Organelle           %T_string;>
<!ELEMENT   OtherReplicons      %T_string;>


<!-- Definition of Structure type: T_DocSum -->
<!ENTITY	 % T_DocSum	"(
 			error
 			| Caption
			| Title
			| Extra
			| Gi
			| CreateDate
			| UpdateDate
			| Flags
			| TaxId
			| Slen
            | Statistics
			| Biomol
			| BioMol
			| MolType
			| Topology
			| SourceDb
			| SegSetSize
			| ProjectId
			| Genome
			| SubType
			| SubName
			| AssemblyGi
			| AssemblyAcc
			| Tech
			| Completeness
			| GeneticCode
			| Strand
			| Organism
			| AccessionVersion
			| Properties
			| Comment
            | Status
			| OSLT
			| ReplacedBy
			| IdGiClass
			| SetType
            | Meta
            | Refseq_accession  
            | GenBank_accession 
            | PubMedIds         
            | Sequencing_centers
            | Reviewed_status   
            | Subtype           
            | GenomeExtra       
            | MoleculeType      
            | DNA_length        
            | Protein_count     
            | RNA_count         
            | Gene_count        
            | Total_count       
            | GC_content        
            | ProjectID         
            | ViewerIdx         
            | TraceGi           
            | ContigNum         
            | NeighborNum       
            | Replicon_type     
            | Replicon_name     
            | Organelle
            | OtherReplicons                     
			)*">

<!ELEMENT DocumentSummary %T_DocSum;>
<!ATTLIST DocumentSummary uid CDATA #IMPLIED>

<!ELEMENT Warning (Otherdb)+>
<!ELEMENT Otherdb   EMPTY>
<!ATTLIST Otherdb
  db    CDATA #IMPLIED
  term  CDATA #IMPLIED
  uid   CDATA #IMPLIED>


<!ELEMENT DocumentSummarySet (DocumentSummary | Warning)*>
<!ATTLIST DocumentSummarySet status CDATA #IMPLIED>

<!ELEMENT eSummaryResult (DocumentSummarySet?)>

=== Klortho/Eutils-JSON/samples/esummary.nucgss.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD eSummaryResult//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSummaryDTD/eSummary_nucgss.dtd">
<eSummaryResult>
    <DocumentSummarySet status="OK">
        <DocumentSummary uid="371566079">
            <Caption>JS583468</Caption>
            <Title>Oct4_065 Buffalo genomic DNA containing POU5F1 (OCT4) binding regions library
                Bubalus bubalis genomic clone CIP065 5-, genomic survey sequence</Title>
            <Extra>gi|371566079|gb|JS583468.1|</Extra>
            <Gi>371566079</Gi>
            <CreateDate>2012/01/09</CreateDate>
            <UpdateDate>2012/01/10</UpdateDate>
            <Flags>0</Flags>
            <TaxId>89462</TaxId>
            <Slen>283</Slen>

            <Biomol>genomic</Biomol>
            <MolType>dna</MolType>
            <Topology>linear</Topology>
            <SourceDb/>
            <SegSetSize>0</SegSetSize>
            <ProjectId>0</ProjectId>
            <Genome/>
            <SubType/>
            <SubName/>
            <AssemblyGi>0</AssemblyGi>
            <AssemblyAcc/>
            <Tech/>
            <Completeness/>
            <GeneticCode/>
            <Strand/>
            <Organism>Bubalus bubalis</Organism>
            <Statistics>
                <Stat type="Length" count="283"/>
                <Stat type="Length" subtype="literal" count="283"/>
                <Stat type="blob_size" count="2048"/>
                <Stat type="pub" count="1"/>
            </Statistics>
            <Properties na="1" gss="8" qual="32">41</Properties>
            <OSLT indexed="yes">JS583468.1</OSLT>
            <AccessionVersion>JS583468.1</AccessionVersion>
        </DocumentSummary>

    </DocumentSummarySet>
</eSummaryResult>
